### ISSUE TITLE
Compile firectl statically?

### ISSUE THREAD

**Issue by luxas** [firecracker-microvm/firectl#15]
Hi, thanks for this great tool!

I wonder, is there a specific reason firectl is not statically linked? (i.e. specific imports)
Otherwise, I think it'd be good as a general best practice to compile it statically to reduce deps :)

**Comment by xibz** [comment]
Hello @luxas,

Thank you for reaching out to us. We've just completed a [release](https://github.com/firecracker-microvm/firectl/releases/tag/v0.1.0) for firectl. If you have any additional questions please let us know!

**Comment by samuelkarp** [comment]
Hi @luxas!  My apologies for the long delay and our failure to answer your question.  We do not have any specific imports that require firectl to be dynamically-linked; it will build and function (as far as I can tell) fine as a statically-linked binary.

As of right now we're building a dynamically-linked binary that links to libc and libpthread, but it can be built either way.  I'll open a PR to add this option to the Makefile.

**Comment by samuelkarp** [comment]
Hi @luxas, we've merged a change to the Makefile to build a statically-linked binary if desired.  You can enable this by passing the `STATIC_BINARY` variable (i.e., `make firectl STATIC_BINARY=1`).

**Comment by luxas** [comment]
Thank you!
