### ISSUE TITLE
Clean external shutdown of the guest VM

### ISSUE THREAD

**Issue by srikantpatnaik** [firecracker-microvm/firectl#16]
Is it possible to implement a proper externally triggered shutdown similar to the `virsh shutdown` functionality in `libvirt`?

**Comment by aghecenco** [comment]
As of https://github.com/firecracker-microvm/firecracker/pull/907 (issue: https://github.com/firecracker-microvm/firecracker/issues/673), Firecracker exposes an API for external shutdown, support for which needs to be added in `firectl`.

**Comment by samuelkarp** [comment]
We'll need to update [firecracker-go-sdk](https://github.com/firecracker-microvm/firecracker-go-sdk) first so we can consume the new API.

**Comment by nmeyerhans** [comment]
Resolved some time ago with #24
