### ISSUE TITLE
Create firectl release

### ISSUE THREAD

**Issue by arun-gupta** [firecracker-microvm/firectl#21]
In order to get started with firectl, it needs to be built:

```
sudo yum install -y git
git clone https://github.com/firecracker-microvm/firectl
sudo amazon-linux-extras install -y golang1.11
cd firectl
make
```

It would be very helpful to have a release, this will make it easy to get started.

**Comment by samuelkarp** [comment]
An initial release is [now available](https://github.com/firecracker-microvm/firectl/releases/tag/v0.1.0).
