### ISSUE TITLE
firectl uses a hardcoded firecracker API socket path

### ISSUE THREAD

**Issue by nmeyerhans** [firecracker-microvm/firectl#3]
Firectl uses `./firecracker.sock` as the firecracker API socket path. This is hardcoded and there's no mechanism for overriding it. This should be fixed:

* The default API socket should be located in a proper temporary location.
* The user should be able to override the default behavior and provide a specific name if desired.

**Comment by IRCody** [comment]
Closing since this option was added in #11. @srikantpatnaik: Hopefully this meets your needs, if not let us know!

**Comment by srikantpatnaik** [comment]
@IRCody Built and tested. Works as expected. Thanks.
